server.port=8093
spring.application.name=loan
spring.profiles.active=dev

management.endpoints.web.exposure.include=*
management.endpoint.shutdown.access=unrestricted
management.info.env.enabled=true


eureka.instance.prefer-ip-address=true
eureka.instance.hostname=localhost
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.client.service-url.defaultZone=${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}

info.app.name=laon
info.app.description=Eazy Bank laon Application
info.app.version=1.0.0


spring.config.import=optional:configserver:${CONFIG_SERVER_HOST:http://localhost:8071}


